package { [
           # 'ack',
           # 'ant',
           # 'arpack',
           # 'autoconf',
           # 'autojump',
           # 'automake',
           # 'bazaar',
           # 'bdw-gc',
           # 'bison',
           # 'boost',
           # 'brew-cask',
           # 'cairo',
           # 'casperjs',
           # 'chromedriver',
           # 'cloog',
           # 'cmake',
           'colordiff',
           # 'cscope',
           # 'ctags',
           # 'daemontools',
           # 'datamash',
           'dos2unix',
           # 'dotwrp',
           # 'emacs',
           # 'erlang',
           # 'fftw',
           # 'fltk',
           # 'fontconfig',
           # 'freetype',
           'gawk',
           # 'gcc',
           # 'gd',
           # 'gdbm',
           # 'gettext',
           # 'gfortran',
           # 'ghc',
           # 'ghostscript',
           # 'git',
           # 'gl2ps',
           # 'glib',
           # 'glpk',
           # 'gmp',
           # 'gnu-sed',
           # 'gnuplot',
           # 'gnutls',
           # 'gobject-introspection',
           # 'gradle',
           # 'graphicsmagick',
           # 'hadoop',
           # 'harfbuzz',
           # 'haskell-platform',
           # 'hdf5',
           'htop-osx',
           # 'hub',
           # 'icu4c',
           # 'imagemagick',
           # 'isl',
           # 'ispell',
           # 'jasper',
           # 'jbig2dec',
           # 'jpeg',
           # 'jpeg-turbo',
           # 'jq',
           # 'leiningen',
           # 'leptonica',
           # 'lftp',
           # 'libevent',
           # 'libffi',
           # 'libmemcached',
           # 'libmpc',
           # 'libnet',
           # 'libpng',
           # 'libssh2',
           # 'libtasn1',
           # 'libtiff',
           # 'libtool',
           # 'libyaml',
           # 'little-cms2',
           # 'lua',
           # 'macvim',
           # 'markdown',
           # 'md5sha1sum',
           # 'memcached',
           # 'mercurial',
           'midnight-commander',
           # 'mobile-shell',
           # 'mpfr',
           # 'multimarkdown',
           # 'nasm',
           # 'ncdu',
           # 'nettle',
           # 'nginx',
           # 'ninja',
           # 'nmap',
           # 'octave',
           # 'openssl',
           # 'optipng',
           # 'ossp-uuid',
           # 'p11-kit',
           'p7zip',
           # 'pango',
           'pcre',
           # 'phantomjs',
           # 'pixman',
           # 'pkg-config',
           # 'protobuf',
           # 'pyqt',
           # 'python',
           # 'qhull',
           # 'qrupdate',
           # 'qscintilla2',
           # 'qt',
           'rabbitmq',
           # 'ragel',
           # 'readline',
           # 'redis',
           # 'rename',
           'rlwrap',
           # 'rtmpdump',
           # 'ruby',
           # 's-lang',
           # 'saxon',
           # 'sbt',
           # 'scala',
           # 'sip',
           # 'sloccount',
           # 'smlnj',
           # 'solr',
           'sqlite',
           'ssh-copy-id',
           # 'suite-sparse',
           # 'szip',
           # 'tbb',
           # 'tcptraceroute',
           # 'tesseract',
           # 'texinfo',
           'the_silver_searcher',
           # 'tig',
           # 'tika',
           'tmux',
           'tree',
           # 'unixodbc',
           # 'valgrind',
           # 'varnish',
           # 'veclibfort',
           # 'w3m',
           # 'wget',
           # 'wxmac',
           # 'xz',
           'youtube-dl',
           # 'zile',
          ]:
          ensure => 'present',
}
